// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZcatoyNdXoo2YTHLvQWeIHBeH3t9avjE',
    appId: '1:287735508308:web:471ae53e99180b9e35acc1',
    messagingSenderId: '287735508308',
    projectId: 'project-management-app-7ace8',
    authDomain: 'project-management-app-7ace8.firebaseapp.com',
    storageBucket: 'project-management-app-7ace8.firebasestorage.app',
    measurementId: 'G-4D2FSK3F09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt5_iIdXP3JpiBigc_cn1YXWmMPuKKFtk',
    appId: '1:287735508308:android:def3ea397262f93b35acc1',
    messagingSenderId: '287735508308',
    projectId: 'project-management-app-7ace8',
    storageBucket: 'project-management-app-7ace8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJuWbVShqFmThVPCvL_dQfLnl9DCcRHRw',
    appId: '1:287735508308:ios:959e743506b8469735acc1',
    messagingSenderId: '287735508308',
    projectId: 'project-management-app-7ace8',
    storageBucket: 'project-management-app-7ace8.firebasestorage.app',
    iosBundleId: 'com.example.projectFrame',
  );
}
