// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ4Z0CuK99pL_frNJjrTSeyu7ezbTs5kU',
    appId: '1:996624453786:web:0b9e60b738aae5349e4f23',
    messagingSenderId: '996624453786',
    projectId: 'khamenkhai',
    authDomain: 'khamenkhai.firebaseapp.com',
    storageBucket: 'khamenkhai.firebasestorage.app',
    measurementId: 'G-0G2Z8WE5T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPSB0r8tiQxvVy3FOHKchx6T-pfJekKKI',
    appId: '1:996624453786:android:c8f4c527bd07a7589e4f23',
    messagingSenderId: '996624453786',
    projectId: 'khamenkhai',
    storageBucket: 'khamenkhai.firebasestorage.app',
  );
}
